const message = {
  INVALID_TOKEN: "Invalid/Expire Token",
  USER_NOT_FOUND: "User not found",
  MISMATCH_PASSWORD: "password is not matched",
  USER_CREATED: "User created successfully",
  USER_SUCCESS_LOGIN: "User has been logged in successfully.",
  COMPANY_CREATED: "Company created successfully",
  COMPANY_NOT_FOUND: "Company not found",
  COMPANY_DATA_UPDATED: "Company data updated successfully",
  COMPANY_DELETE: "Company data deleted successfully",
  PARTY_CREATED: "Party created successfully",
  PARTY_NOT_FOUND: "Party not found",
  USER_NOT_FOUND: "User not found",
  PARTY_DATA_UPDATED: "Party data updated successfully",
  PARTY_DELETE: "Party data deleted successfully",
  USER_DATA_UPDATED: "User data updated successfully",
  USER_DELETE: "User data deleted successfully",
  UNIQUE_USER: "User details should be Unique",
  COLORYARN_CREATED: "ColorYarn created successfully",
  COLORYARN_NOT_FOUND: "ColorYarn not found",
  MATCHING_NOT_AVAILABLE:"Selected design matching is not available",
  COLORYARN_DATA_UPDATED: "ColorYarn data updated successfully",
  COLORYARN_DELETE: "ColorYarn data deleted successfully",
  DESIGN_CREATED: "Design Data created successfully",
  DESIGN_NOT_FOUND: "Design not found",
  DESIGN_DATA_UPDATED: "Design data updated successfully",
  DESIGN_DELETE: "Design data deleted successfully",
  MATCHING_CREATED: "Matching created successfully",
  DONT_REPEAT_SAME_COLOR: "Do not repeat same color combination",
  COLORDESIGN_NOT_FOUND: "ColorDesign not found",
  MATCHING_NOT_FOUND: "Matching not found",
  MATCHING_SUCCESSFUL: "Matching find successfully",
  MATCHING_DATA_UPDATED: "Matching data updated successfully",
  MATCHING_DELETE: "Matching data deleted successfully",
  MACHINE_CREATED: "Machine created successfully",
  MACHINE_NOT_FOUND: "Machine not found",
  MACHINE_DATA_UPDATED: "Machine data updated successfully",
  MATCHING_DETAILS_NOT_FOUND: "Matching Detail is not found",
  MACHINE_DELETE: "Machine data deleted successfully",
  IMAGE_NOTFOUND: "Image is not available in folder",
  YARN_PURCHASE_CREATED: "Yarn purchase created successfully",
  YARNPURCHASE_NOT_FOUND: "YarnPurchase not found",
  YARNPURCHASE_DATA_UPDATED: "YarnPurchase data updated successfully",
  YARNPURCHASE_DELETE: "YarnPurchase data deleted successfully",
  YARNPURCHASE_NOT_FOUND: "YarnPurchase not found",
  YARN_SALES_CREATED: "Yarn sales created successfully",
  YARNSALES_NOT_FOUND: "YarnSales not found",
  YARNSALES_DATA_UPDATED: "YarnSales data updated successfully",
  YARNSALES_DELETE: "YarnSales data deleted successfully",
  COLORCODE_DATA_FOUND: "ColorCOde data find successfully",
  COLORCODE_DATA_NOTFOUND: "ColorCOde data not found",
  ORDER_CREATED: "Order created successfully",
  DESIGN_DIFFERANCE: "Order design can not be same",
  ORDERDESIGN_DELETE: "Order design deleted successfully",
  ORDERD_DELETE: "Order deleted successfully",
  ORDERID_CREATED: "Order ID created successfully",
  ORDER_NOT_FOUND: "Order not found.",
  ORDER_UPDATED: "Order updated successfully.",
  PURCHASE_NOT_FOUND: "purchaseDetails are not found!",
  SALES_NOT_FOUND: "salesDetails are not found!",
  WEIGHT_DIFFERENCE: "Yarn stock is not enough for sale",
  IT_IS_SAME_FEEDERS: "You can not add same feeders.",
  ORDER_DELETE: "Order deleted successfully",
  PROCESS_ORDER_SUCESS: "Order process created successfully",
  COMPLETE_ORDER_SUCESS: "Complete Order created successfully",
  SETTLE_ORDER_SUCESS: "Settle Order created successfully",
  MATCHING_FEEDER_SUCCESS: "Matching feeders find successfully.",
  ORDER_MACHINE_NOT_FOUND: "Order on machine can not found.",
  ORDER_FIND_SUCCESSFULLY: "Order find sucdcessfully.",
  DESIGN_FIND_SUCCESSFULLY: "Party Design Find Successfully."
};
module.exports = message;
